---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---



```{r getData, eval=FALSE}
link='https://github.com/qziegler/VisualAnalytics_2_tabularData/raw/master/data_forclass/FY2017_DCCrimeData.csv'

#getting the data TABLE from the file in the cloud:
mydata=read.csv(link)
```


```{r}
table(mydata$OFFENSE, exclude = 'nothing')
```

```{r}
absoluteT=table(mydata$OFFENSE, exclude = 'nothing')
```

```{r}
absoluteTOrd=sort(absoluteT, decreasing = TRUE)
```

```{r}
prop.table(absoluteTOrd)
```

```{r}
ToPlot=prop.table(absoluteT)
ToPlot=ToPlot*100
```

```{r}
ToPlotOrd=prop.table(absoluteTOrd)
ToPlotOrd=ToPlotOrd*100
```

```{r}
paletteHere=topo.colors(length(ToPlotOrd))
```


```{r}
barplot(ToPlotOrd,
        col = paletteHere,
        cex.names = .5,
        las = 2,
        horiz = T)

```

```{r}
plotLabels=paste0(round(ToPlotOrd,2),'%') # labels for the slices

location=barplot(ToPlotOrd,
         col = paletteHere,
         border=NA,
         xlim=c(0,100), 
         xlab = '(in %)',
         horiz = T,
        las = 1,
         cex.names = .75,
         cex.lab= 1,
         xaxt="n") # no x-axis, so I customize it below...

text(x=ToPlotOrd,y = location,labels=plotLabels,pos = 4,cex = 1)  
```


```{r}
library(ggplot2)
```

```{r}
tableFreq=as.data.frame(ToPlot)
names(tableFreq)=c("OFFENSE","pct")
#you have:
tableFreq
```
```{r}
tableFreqO=tableFreq[order(tableFreq$pct),]
```

```{r}
base = ggplot(tableFreqO, aes(x=OFFENSE,pct)) 
lolliplot1=base + geom_segment(aes(y = 0, 
                                   x = OFFENSE, 
                                   yend = pct, 
                                   xend = OFFENSE), color = "BLUE") 
lolliplot2 = lolliplot1 + geom_point()
lolliplot2 + scale_x_discrete(limits=tableFreqO$OFFENSE) # key element
```


```{r}
tableFreqO$gap=tableFreqO$pct-25
tableFreqO$PositiveGap=ifelse(tableFreqO$gap>0,T,F)

# add new aesthetics 'color'
base = ggplot(tableFreqO, aes(OFFENSE,gap,
                              color=PositiveGap)) #change
lolliplot1=base + geom_segment(aes(y = 0, 
                                   x = OFFENSE, 
                                   yend = gap, 
                                   xend = OFFENSE), color = "gray") 
lolliplot2 = lolliplot1 + geom_point()
lolliplot2 + scale_x_discrete(limits=tableFreqO$OFFENSE) # key element
lolliplot3 = lolliplot2 + scale_x_discrete(limits=tableFreqO$locale) 
# annotating and moving the text on the horizontal
```

```{r}
lolliplot4 = lolliplot3 + coord_flip()
lolliplot4
```

